spring:
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:log4jdbc:mysql://117.17.142.207:3306/realestate_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: cs616
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 127.0.0.1
    password: ""
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
server:
  port: 8090


